name: Add changeset from conventional commits

on:
  pull_request:
    types: [opened, synchronize]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  call:
    uses: sanity-io/.github/.github/workflows/changesets-from-conventional-commits.yml@main
    if: github.event.pull_request.user.login == 'renovate[bot]' || github.event.pull_request.user.login == 'squiggler-legacy[bot]' || github.event.pull_request.user.login == 'squiggler-app[bot]'
    secrets:
      ECOSPARK_APP_ID: ${{ secrets.ECOSPARK_APP_ID }}
      ECOSPARK_APP_PRIVATE_KEY: ${{ secrets.ECOSPARK_APP_PRIVATE_KEY }}
